main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
]

programa/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("Lista-Programa/",views.ListaPrograma, name="ListaPrograma"),
	path("Adisiona-Dadus-Programa/",views.addPrograma, name="addPrograma"),
	
	path("Lista-Implementasaun-Programa/",views.ListaImplementasaun, name="ListaImplementasaun"),
	path("Mapa-Lokalizasaun-Implementasaun-Programa-Hotu-Hotu/",views.mapaLokalizasaunImplementasaunPrograma, name="mapaLokalizasaunImplementasaunPrograma"),
	path("Adisiona-Dadus-Implementasaun-Programa/",views.addImplementasaun, name="addImplementasaun"),
	path("Altera-Dadus-Implementasaun-Programa/<str:hashid>/<str:page>",views.updateImplementasaun, name="updateImplementasaun"),
	path("Detallu-Dadus-Implementasaun-Programa/<str:hashid>",views.detalluImplementasaunPrograma, name="detalluImplementasaunPrograma"),
	path("Delete-Dadus-Implementasaun-Programa/<str:hashid>",views.deleteImplementasaun, name="deleteImplementasaun"),
	path("Xave-Dadus-Implementasaun-Programa/<str:hashid>/<str:page>",views.lockImplementasaunPrograma, name="lockImplementasaunPrograma"),
	path("Loke-Dadus-Implementasaun-Programa/<str:hashid>/<str:page>",views.unlockImplementasaunPrograma, name="unlockImplementasaunPrograma"),
	path("Manda-Dadus-Implementasaun-Programa/<str:hashid>/<str:page>",views.mandaImplementasaunPrograma, name="mandaImplementasaunPrograma"),
	path("Adisiona-Dadus-Lokalizasaun-Implementasaun-Programa/<str:hashid>",views.addImplementationLocation, name="addImplementationLocation"),
	path("Update-Dadus-Lokalizasaun-Implementasaun-Programa/<str:hashid>",views.updateMapaLokalizasaunImplementasaun, name="updateMapaLokalizasaunImplementasaun"),
	
	path("Update-Status-Implementasaun-Programa/",views.updateStatusImplementasaun, name="updateStatusImplementasaun"),

	path("Lista-Implementasaun-Programa/<str:hashid>",views.listaImplementasaunPrograma, name="listaImplementasaunPrograma"),


]

programa/models.py
from django.db import models
from django.contrib.auth.models import User
from custom.models import *
from survey.models import Survey
from monitoring.models import ImplementationMonitoring,PostImplementationMonitoring

# Create your models here.

class Programa(models.Model):
	naran = models.CharField(max_length=200, null=True)
	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True,blank=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def getTotalImplementation(self):
		return Implementasaun.objects.filter(programa=self,is_approved=True).count()

	def __str__(self):
		template = '{0.naran}'
		return template.format(self)

class Implementasaun(models.Model):
	survey = models.OneToOneField(Survey,on_delete=models.SET_NULL,null=True,blank=True)
	programa = models.ForeignKey(Programa,on_delete=models.CASCADE,null=True)
	village = models.ForeignKey(Village, on_delete=models.CASCADE,null=True)
	administrativepost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE,null=True)
	municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE,null=True)
	startdate = models.DateField(null=True)
	enddate = models.DateField(null=True)
	montanteOsanAlokasaun = models.DecimalField(default=0,decimal_places=2,max_digits=10,verbose_name="Orsamentu Alokasaun",null=True)
	is_locked = models.BooleanField(default=False, null=True, blank=True)
	is_sent = models.BooleanField(default=False, null=True, blank=True)
	is_approved = models.BooleanField(default=False, null=True, blank=True)
	is_rejected = models.BooleanField(default=False, null=True, blank=True)
	rejected_info = models.TextField(null=True,blank=True)
	description = models.TextField(null=True,blank=True)
	partisipasaunF = models.IntegerField(verbose_name="Partisipasaun Feto",null=True)
	partisipasaunM = models.IntegerField(verbose_name="Partisipasaun Mane",null=True)
	totalTekniku = models.IntegerField(verbose_name="Total Tekniku",null=True)
	partisipasaunP = models.IntegerField(verbose_name="Partisipasaun Populasaun",null=True)
	statusImplementasaun = models.CharField(choices=[('Not Start','Not Start'),('On Going','On Going'),('Pending','Pending'),('Abandone','Abandone'),('Complate','Complate')],default="Not Start",max_length=30,null=True,blank=True)
	image = models.ImageField(upload_to='ImplementasaunPrograma', null=True,blank=True)
	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def getLastImpelementationMonitoring(self):
		return ImplementationMonitoring.objects.filter(implementasaun=self,is_approved=True).last()

	def getImpelementationMonitoring(self):
		return ImplementationMonitoring.objects.filter(implementasaun=self).all()

	def getPostImpelementationMonitoring(self):
		return PostImplementationMonitoring.objects.filter(implementasaun=self).all()

	def __str__(self):
		template = '{0.programa} {0.village}'
		return template.format(self)

class ImplementasaunPoint(models.Model):
	implementasaun = models.OneToOneField(Implementasaun, on_delete=models.CASCADE, null=True,related_name="implementationLocation")
	latitude = models.CharField(max_length=20, null=True, blank=True)
	longitude = models.CharField(max_length=20, null=True, blank=True)
	image = models.ImageField(upload_to='implementationLocation', null=True,blank=True)

	def __str__(self):
		template = '{0.implementasaun}'
		return template.format(self)

charts/views/programa.py
from django.shortcuts import render,redirect, get_object_or_404,HttpResponse
from django.http import JsonResponse
from django.contrib.auth.models import Group,User
from django.contrib.auth.decorators import login_required
from programa.models import *
from custom.utils import *
from funsionariu.models import UserFunsionariu

@login_required
def ChartSumariuPrograma(request):
	group = request.user.groups.all()[0].name
	labels = []
	data = []
	listaPrograma = Programa.objects.all()
	if group == "eip":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,village=funsionariu.funsionariu.village).count()
			labels.append(x.naran)
			data.append(totalImplementasaun)
	if group == "fun":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,administrativepost=funsionariu.funsionariu.administrativepost).count()
			labels.append(x.naran)
			data.append(totalImplementasaun)
	if group == "admin" or group == "dir":
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,is_approved=True).count()
			labels.append(x.naran)
			data.append(totalImplementasaun)

	return JsonResponse(data={
		'labels':labels,
		'data':data,
		})

@login_required
def ChartStatusImplementasaunPrograma(request):
	group = request.user.groups.all()[0].name
	listaPrograma = Programa.objects.all()
	status = Implementasaun.objects.filter(is_approved=True).distinct().values('statusImplementasaun').all()
	label,obj,programLabel,statusList = list(),list(),list(),list()
	for a in listaPrograma.iterator():
		programLabel.append(a.naran)
	for i in status:
		statusList.append(i['statusImplementasaun'])
	if group == "eip":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for cjj in statusList:
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id,village=funsionariu.funsionariu.areavillage,is_approved=True,statusImplementasaun=cjj).all().count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj)
			obj.append(totalImplementasaun)
	if group == "fun":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for cjj in statusList:
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id,administrativepost=funsionariu.funsionariu.areaadministrativepost,is_approved=True,statusImplementasaun=cjj).all().count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj)
			obj.append(totalImplementasaun)
	if group == "admin" or group == "dir":
		for cjj in statusList:
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id,is_approved=True,statusImplementasaun=cjj).all().count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj)
			obj.append(totalImplementasaun)

	return JsonResponse(data={
		'programLabels':programLabel,
		'labels':label,
		'data':obj,
		})

@login_required
def ChartImplementasaunProgramaArea(request):
	group = request.user.groups.all()[0].name
	listaPrograma = Programa.objects.all()
	label,obj,programLabel = list(),list(),list()
	for a in listaPrograma.iterator():
		programLabel.append(a.naran)
	if group == "eip":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for cjj in statusList:
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id,village=funsionariu.funsionariu.areavillage,is_approved=True,statusImplementasaun=cjj).all().count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj)
			obj.append(totalImplementasaun)
	if group == "fun":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		listaArea = Village.objects.filter(administrativepost__id=funsionariu.funsionariu.areaadministrativepost.id).all()
		for cjj in listaArea.iterator():
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id,village__id=cjj.id,is_approved=True).all().count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj.name)
			obj.append(totalImplementasaun)
	if group == "admin" or group == "dir":
		listaArea = Municipality.objects.all()
		for cjj in listaArea.iterator():
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id,municipality__id=cjj.id,is_approved=True).all().count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj.name)
			obj.append(totalImplementasaun)
	return JsonResponse(data={
		'programLabels':programLabel,
		'labels':label,
		'data':obj,
		})


@login_required
def ChartImplementasaunProgramaYear(request):
	group = request.user.groups.all()[0].name
	listaPrograma = Programa.objects.all()
	label,obj,programLabel = list(),list(),list()
	for a in listaPrograma.iterator():
		programLabel.append(a.naran)
	if group == "eip":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for cjj in statusList:
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id,village=funsionariu.funsionariu.areavillage,is_approved=True,statusImplementasaun=cjj).all().count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj)
			obj.append(totalImplementasaun)
	if group == "fun":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		IP_years = Implementasaun.objects.filter(administrativepost__id=funsionariu.funsionariu.areaadministrativepost.id).distinct().values('startdate__year').all()
		for cjj in IP_years.iterator():
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(administrativepost__id=funsionariu.funsionariu.areaadministrativepost.id,programa__id=x.id, startdate__year=cjj['startdate__year'], is_approved=True).count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj['startdate__year'])
			obj.append(totalImplementasaun)
	if group == "admin" or group == "dir":
		IP_years = Implementasaun.objects.filter().distinct().values('startdate__year').all()
		for cjj in IP_years.iterator():
			totalImplementasaun = []
			for x in listaPrograma.iterator():
				cjj_a = Implementasaun.objects.filter(programa__id=x.id, startdate__year=cjj['startdate__year'], is_approved=True).count()
				totalImplementasaun.append(cjj_a)
			label.append(cjj['startdate__year'])
			obj.append(totalImplementasaun)

	return JsonResponse(data={
		'programLabels':programLabel,
		'labels':label,
		'data':obj,
		})

programa/views/programa.py
from django.shortcuts import render,redirect, get_object_or_404,HttpResponse
from django.contrib.auth.models import Group,User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import *
from custom.utils import *
from ..forms import *
from funsionariu.models import UserFunsionariu
from users.decorators import allowed_users
# Create your views here.
@login_required
@allowed_users(allowed_roles=['dir','admin','eip','fun'])
def ListaPrograma(request):
	group = request.user.groups.all()[0].name
	listaPrograma = Programa.objects.all()
	sumariuPrograma = []
	if group == "eip":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,village=funsionariu.funsionariu.village).count()
			sumariuPrograma.append({'hashed':x.hashed,'naran':x.naran,'totalImplementasaun':totalImplementasaun})
	if group == "fun":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,administrativepost=funsionariu.funsionariu.areaadministrativepost).count()
			sumariuPrograma.append({'hashed':x.hashed,'naran':x.naran,'totalImplementasaun':totalImplementasaun})
	if group == "admin" or group == "dir":
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,is_approved=True).count()
			sumariuPrograma.append({'hashed':x.hashed,'naran':x.naran,'totalImplementasaun':totalImplementasaun})
	context = {
		"title":"Sumariu Programa PNDS",
		"active_programa":"active",
		"page":"list",
		"listaPrograma":sumariuPrograma,
	}
	return render(request, "ListaPrograma.html",context)

@login_required
@allowed_users(allowed_roles=['dir','admin'])
def addPrograma(request):
	if request.method == "POST":
		_, newid = getlastid(Programa)
		hashid = hash_md5(str(newid))
		form = ProgramaForm(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.hashed = hashid
			instance.user_created = request.user
			instance.save()
			messages.success(request, f'Dadus Programa Adisiona ho Susesu.')
			return redirect('ListaPrograma')
	else:
		form = ProgramaForm()
	
	context ={
		"title":"Adisiona Programa",
		"form":form,
		"active_programa":"active",
		"page":"form",
	}
	return render(request,'ListaPrograma.html',context)
	
@login_required
@allowed_users(allowed_roles=['dir','admin','eip','fun'])
def listaImplementasaunPrograma(request,hashid):
	group = request.user.groups.all()[0].name
	programa = get_object_or_404(Programa,hashed=hashid)
	if group == "eip":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		listaImplementasaun = Implementasaun.objects.filter(programa=programa,village=funsionariu.funsionariu.village).all().order_by('-id')
		listaPrograma = Programa.objects.all()
		sumariuPrograma = []
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,village=funsionariu.funsionariu.village).count()
			sumariuPrograma.append({'hashed':x.hashed,'naran':x.naran,'totalImplementasaun':totalImplementasaun})
	if group == "fun":
		funsionariu = get_object_or_404(UserFunsionariu,user__id=request.user.id)
		listaImplementasaun = Implementasaun.objects.filter(programa=programa,administrativepost=funsionariu.funsionariu.areaadministrativepost).all().order_by('-id')
		listaPrograma = Programa.objects.all()
		sumariuPrograma = []
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,administrativepost=funsionariu.funsionariu.areaadministrativepost).count()
			sumariuPrograma.append({'hashed':x.hashed,'naran':x.naran,'totalImplementasaun':totalImplementasaun})
	if group == "admin" or group == "dir":
		listaImplementasaun = Implementasaun.objects.filter(programa=programa,is_approved=True).all().order_by('-id')
		listaPrograma = Programa.objects.all()
		sumariuPrograma = []
		for x in listaPrograma.iterator():
			totalImplementasaun = Implementasaun.objects.filter(programa__id=x.id,is_approved=True).count()
			sumariuPrograma.append({'hashed':x.hashed,'naran':x.naran,'totalImplementasaun':totalImplementasaun})
	context = {
		"title":f"Lista Implementasaun Programa {programa.naran}",
		"listaImplementasaun":listaImplementasaun,
		"sumariuPrograma":sumariuPrograma,
	}
	return render(request, "ListaImplementasaunPrograma.html",context)

programa/templates/ListaImplementasaun.html
{% extends "main/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block headStyle %}
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
{% endblock %}
{% block content %}
	<section>
        <div class="container mt-5 border border-danger p-3">
          <!-- Page Header-->
          <header> 
            <ol class="breadcrumb mb-1 mt-1">
              <li class="breadcrumb-item"><a href="{% url 'home' %}">Varanda</a></li>
              {% if page == "form" %}
              <li class="breadcrumb-item"><a href="{% url 'ListaImplementasaun' %}">Lista Implementasaun Programa</a></li>
              {% endif %}
              <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
            </ol>
          </header>
                    {% if messages %}
                        {% for message in messages %} 
                            <div id="divmessage" class="alert alert-{{ message.tags }} alert-dismissable">
                              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                              {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
          {% if page == "list" %}
          <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-header d-flex justify-content-between text-center">
                  <div>
                  </div>
                  <div class="d-flex justify-content-between">
                     <a href="{% url 'addImplementasaun' %}" class="btn btn-sm btn-info mr-2" title="Add Data"> <i class="fa fa-plus-square"></i> Adisiona Implementasaun</a>
                  </div>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table id="example"  class="table table-hover table-striped">
                      <thead>
                        <tr>
                          <th>Nu</th>
                          <th>Programa</th>
                          <th class="text-center"><i class="fa fa-image"></i></th>
                          <th>Suku</th>
                          <th>Postu</th>
                          <!-- <th>Munisipiu</th> -->
                          <th>Data</th>
                          <th>Status</th>
                          <th>Progresu</th>
                          <th class="text-center">Asaun</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for data in listaInplementasaun %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{ data.programa }}</td>
                          <td class="text-center">{% if data.image %}<a href="{{data.image.url}}" target="_blank"><img src="{{data.image.url}}" width="50px" height="50px"></a>{%else%}{%endif%}</td>
                          <td>{{ data.village }}</td>
                          <td>{{ data.administrativepost }}</td>
                          <!-- <td>{{ data.municipality }}</td> -->
                          <td>{{ data.date|date:"d-M-Y" }}</td>
                          <td>{{ data.statusImplementasaun }}</td>
                          <td>{% if data.is_approved %}Aprova Ona{%else%}Seidauk Aprova{%endif%}
                            {% if data.is_rejected %}<sub class="badge-secondary pr-1 pl-1">Rejeita</sub>{% elif data.is_sent == True and data.is_approved == False %}<sub class="badge-secondary pr-1 pl-1">Prosesu</sub>{%endif%}</td>
                          <td>
                            <div class="d-flex justify-content-center"> 
                              {% if data.is_sent == False and data.is_rejected == False %}
                                {% if data.is_locked == False %}
                                <div class="flex-fill mr-1"><a href="{% url 'updateImplementasaun' data.hashed 'list' %}" class="btn btn-sm btn-success" title="Altera Implementasaun Programa"><i class="fa fa-pencil"></i> </a></div>
                                <div class="flex-fill mr-1"><a href="{% url 'lockImplementasaunPrograma' data.hashed 'list' %}" class="btn btn-sm btn-danger" title="Xave dadus"><i class="fa fa-lock"></i> </a></div>
                                {% else %}
                                <div class="flex-fill mr-1"><a href="{% url 'mandaImplementasaunPrograma' data.hashed 'list' %}" class="btn btn-sm btn-warning" title="Manda"><i class="fa fa-send"></i> </a></div>
                                <div class="flex-fill mr-1"><a href="{% url 'unlockImplementasaunPrograma' data.hashed 'list' %}" class="btn btn-sm btn-danger" title="Xave dadus"><i class="fa fa-unlock"></i> </a></div>
                                {% endif %}
                              {% endif %}
                              <div class="flex-fill mr-1"><a href="{% url 'detalluImplementasaunPrograma' data.hashed %}" class="btn btn-sm btn-info" title="Detallu Programa"><i class="fa fa-list"></i> </a></div>
                            </div>  
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr/>
            <ol class="breadcrumb mb-2 mt-1">
            {% for t in sumariuPrograma %}
                <li class="breadcrumb-item"><a href="{% url 'listaImplementasaunPrograma' t.hashed %}">{{ t.naran }} <span class="badge badge-warning">{{ t.totalImplementasaun }}</span></a></li>
            {% endfor %}
            </ol>
          {%endif%}
          {% if page == "form" %}
          <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-header d-flex justify-content-between text-center">
                </div>
                <div class="card-body">
                  {% csrf_token %}
                  {% crispy form %}
                </div>
              </div>
            </div>
          </div>
          <script src="{% static 'main/js/jquery.min.js'%}"> </script>
          <script type="text/javascript">
            $("#id_municipality").change(function () {
              var municipalityId = $(this).val();
              $.ajax({
                url: "{% url 'ajax_load_posts' %}",
                data: {
                  'municipality': municipalityId
                },
                success: function (data) {
                  $("#id_administrativepost").html(data);
                }

              });
            });
            $("#id_administrativepost").change(function () {
              var postId = $(this).val();
              $.ajax({
                url: "{% url 'ajax_load_villages' %}",
                data: {
                  'post': postId
                },
                success: function (data) {
                  $("#id_village").html(data);
                }
              });

            });
            //load Imagen
            function myFunction() {
              var image = document.getElementById("output");
              image.src = URL.createObjectURL(event.target.files[0]);
            }
          </script>
          {%endif%}
          {% if page == "addLocation" %}
            <div class="row">
              <div class="col-lg-12">
                <div class="card">
                  <div class="card-header">
                      
                  </div>
                  <div class="card-body">
                    <form method="post" action="">
                    {% csrf_token %}
                      <div class="form-group">
                        <label for="Latitude">Latitude :</label>
                        <input class="form-control" type="text" id="lat" name="lat" placeholder="Your lat..">
                      </div>
                      <div class="form-group">
                        <label for="Longitude">Longitude :</label>
                        <input class="form-control" type="text" id="lng" name="lng" placeholder="Your lng..">
                      </div>
                      <div id="map" style="width: 100%;height: 400px"></div>
                      <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDoukaK1udD0Z4erUsxwkYzRKTOWmJid34"></script>
                  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDoukaK1udD0Z4erUsxwkYzRKTOWmJid34&libraries=places"></script>
                      <script type="text/javascript" language="javascript" src="{% static 'main/mapa/formMapa.js' %}"></script>
                      <div class="card-footer">
                          <div class="text-right">
                              <a href="#" class="btn btn-sm btn-warning" onclick=self.history.back()>Cancel</a>
                              <input type="submit" name="submit" value="Save" class="btn btn-sm btn-primary">
                          </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        </div>
      </section>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $(document).ready( function () {
        var table = $('#example').removeAttr('width').DataTable( {
            
        });
    } );
</script>
{% endblock %}